name: Release Build

on:
  release:
    types: [published]

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Azure Function artifact
        run: |
          mkdir -p azure_function_release
          cp *.py azure_function_release/
          cp requirements.txt azure_function_release/
          cp host.json azure_function_release/

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: azure-function-release
          path: azure_function_release/

      - name: Upload assets to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: azure_function_release/*
          asset_name: ${{ github.event.release.tag_name }}-release.zip
          asset_content_type: application/zip